# taken from https://dev.to/abulka/comment/1dh3k thanks!
name: Release Catalyst (Dev)
on: 
  workflow_dispatch
  push:
    tags:
      - "*"
jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
        - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
        - name: Set Version
        run: npm version $TAG_NAME
        env:
          TAG_NAME: nightly-tag-${{ steps.date.outputs.date }}
          RELEASE_NAME: nightly-release-${{ steps.date.outputs.date }}
      - name: Install dependencies
        run: npm install
      - name: Get tailwind styles
        run: npm run tailwind:once
      - name: Publish to release using Electron Forge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish
      - name: Apple Silicon
        if: ${{ matrix.os == 'macos-latest' }}
        run: npm run publish -- --arch=arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
