name: Validate
on: 
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
  
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: The-Catalyst-Browser-Project/ci-auto-release@main
      
